### ISSUE TITLE
[Epic] Argocd to Dev

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#52]
This epic is to describe how to do to migrate argocd to the dev environment. How we plan on deploying it, test it, which applications will be transfered and are therefore not handled by the cloud team. Etc.

Note: The current issues referenced are the work that was done. Not the future issues to do to incorporate said work into the manifest.

# Rollout
The idea would be to do it in waves. The first wave being any mandatory things. Afterward, the approach would be more granular, following the specific applications we want. 
The general idea would be to get the equivalent of what we currently have, but using argocd. Then after that is done, do the 1.3 upgrade.

# The applications
This is the list of all the applications we touched in the other epic. Most of them could be removed since it is things that are handled by cloud. (WIP/To confirm) 
## First Wave
Definetly need: 
- [ ]  Rollout of jupyter-web-app  https://github.com/StatCan/aaw-argocd-manifests/issues/30
#8
- [ ]  application/pipeline  https://github.com/StatCan/aaw-argocd-manifests/issues/39
#12
- [ ]  application/centraldashboard https://github.com/StatCan/aaw-argocd-manifests/issues/32
#7
- [ ]  application/jupyter-web-app/configs https://github.com/StatCan/aaw-argocd-manifests/issues/40
#9
- [ ]  application/notebook-controller https://github.com/StatCan/aaw-argocd-manifests/issues/41
#10
- [ ]  application/prob-notebook-controller https://github.com/StatCan/aaw-argocd-manifests/issues/42
#13

Possibly:
- [ ]  Argoflow Manifest - application/katib 
#23 : do we actually  want Katib?
- [ ]  Argoflow manifest - metacontroller 
#22
- [ ]  application/seldon 
#5
- [ ]  application/admission-webhook 
#14
- [ ]  application/profiles 
#19
- [ ]  application/kubeflow-roles 
#16
- [ ]  application/metadata 
#17
- [ ]  Argoflow manifest verify namespaces 
#20
- [ ]  Fix up OIDC-Auth 
 #48
- [ ]  Argoflow Manifest kfserving 
#24
- [ ]  Argoflow Manifest knative
 #25
- [ ]  Argoflow manifest - oidc-authservice 
#21
- [ ]  application/mysql 
#18

## Not doing:
Not relevant/handled by cloud:
- [ ] ~~application/argo #15~~
- [ ]  ~~application/minio #11~~
- [ ]  ~~ArgoCD - Downgrade Istio #35~~
## Second wave
Second priority - will be done after the first wave
- [ ]  Argoflow Manifest application/pytorch-job 
#26
- [ ]  application/spark-operator 
#6
- [ ]  Argoflow Manifest application/tf-training 
#27
- [ ]  Argoflow Manifest application/mxnet-job 
#28
- [ ]  Argoflow Manifest application/mpi-job 
#29

# Change in structure
Migrate the kubeflow folder in the manifest repo. 
Use overlays to use more appropriate sizes for dev vs prod. https://github.com/StatCan/aaw-argoflow-azure/issues/51

**Comment by rohank07** [comment]
Closing this Epic: New & updated epic created here https://github.com/StatCan/aaw-kubeflow-manifests/issues/111
